## Modin - Pandas 

- How to speed up Pandas by 4X

In [2]:
### Read  in the data with pandas
import pandas as pd
import time

s = time.time()
df = pd.read_csv("wine.csv")
e=time.time()
print("Pandas Loading Time = {}".format(e-s))


### Read in the data with Modin
!pip install modin
import modin.pandas as pd

s = time.time()
df = pd.read_csv("wine.csv")
e = time.time()
print("Modin Loading TIme = {}".format(e-s))

Pandas Loading Time = 0.0076181888580322266
Collecting modin
  Using cached modin-0.15.1-py3-none-any.whl (868 kB)
Requirement already satisfied: fsspec in c:\programdata\anaconda3\lib\site-packages (from modin) (2022.2.0)
Requirement already satisfied: pandas==1.4.2 in c:\programdata\anaconda3\lib\site-packages (from modin) (1.4.2)
Requirement already satisfied: numpy>=1.18.5 in c:\programdata\anaconda3\lib\site-packages (from modin) (1.21.5)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from modin) (21.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\programdata\anaconda3\lib\site-packages (from pandas==1.4.2->modin) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas==1.4.2->modin) (2021.3)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas==1.4.2->modin) (1.16.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\programdata\anaconda3\lib\site-packages (from packaging->modin) (3.0.4)
Installing collected packages: modin
Successfully installed modin-0.15.1

UserWarning: Dask execution environment not yet initialized. Initializing...
To remove this warning, run the following python code before doing dataframe operations:

    from distributed import Client

    client = Client()

Modin Loading TIme = 16.80442476272583

In [6]:
import modin.pandas as pd
import numpy as np 

frame_data = np.random.randint(0,100, size=(2**10,2**8))
df = pd.DataFrame(frame_data)

UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.

In [7]:
df.shape

(1024, 256)

In [8]:
df.to_csv('test_31.csv')

UserWarning: `to_csv` defaulting to pandas implementation.
Please refer to https://modin.readthedocs.io/en/stable/supported_apis/defaulting_to_pandas.html for explanation.

In [9]:
%%time
import pandas as pd
pd.read_csv('https://raw.githubusercontent.com/MateLabs/Public-Datasets/master/Datasets/wine.csv')

CPU times: total: 250 ms
Wall time: 737 ms

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,one
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,one
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,one
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,one
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,three
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,three
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,three
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,three
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,three

In [10]:
%%time
import modin.pandas as pd
pd.read_csv('https://raw.githubusercontent.com/MateLabs/Public-Datasets/master/Datasets/wine.csv')

UserWarning: Parameters provided defaulting to pandas implementation.

CPU times: total: 141 ms
Wall time: 291 ms

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,one
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,one
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,one
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,one
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,three
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,three
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,three
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,three
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,three

In [12]:
import time
import pandas as pd
df = pd.read_csv('test_31.csv')
s = time.time()
df = pd.concat([df for _ in range(100)])
e = time.time()
print("Pandas Concat Time = {}".format(e-s))

Pandas Concat Time = 0.16977882385253906

In [15]:
import time
import modin.pandas as pd
df = pd.read_csv('test_31.csv')
s = time.time()
df = pd.concat([df for _ in range(100)])
e = time.time()
print("Modin Pandas Concat Time = {}".format(e-s))

Modin Pandas Concat Time = 17.32911729812622

In [14]:
## Sometime Modin is Faster Than Original Libraries of Pandas Itself Sometimes it is very Slow